import{S as d,N as u,K as m,M as p,A as f,a as w}from"./assets/vendor-b0440692.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();new d("#swiperAbout",{modules:[u,m,p],navigation:{nextEl:".about-me-btn-swipe"},mousewheel:{invert:!0},keyboard:{enabled:!0,onlyInViewport:!0},mousewheel:!0,touch:!0,centeredSlides:!1,loop:!0,speed:500,spaceBetween:0,slideToClickedSlide:!0,allowTouchMove:!0,slideActiveClass:"current-skill",slidesPerView:2,width:260,breakpoints:{768:{slidesPerView:3,width:600},1440:{slidesPerView:6,width:1264}}});const y=document.querySelectorAll(".ac-item-information");y.forEach(o=>{o.addEventListener("click",()=>{o.classList.toggle("active")})});new f(".faq-list",{elementClass:"faq-item",triggerClass:"faq-question",panelClass:"faq-answer",showMultiple:!0});const h={reviewsList:document.querySelector(".reviews-list"),previousBtn:document.querySelector(".previous-btn"),nextBtn:document.querySelector(".next-btn")};document.querySelector(".reviews-list");window.addEventListener("DOMContentLoaded",async()=>{try{(await w.get("https://portfolio-js.b.goit.study/api/reviews")).data.forEach(r=>{const n=document.createElement("div");n.classList.add("review-item"),n.innerHTML=`<li class="reviews-item">
         <img
           src="${r.avatar_url}"
           alt="author's photo"
           class="review-photo"
           width="48px"
           height="48px"
         />
         <p class="review-author">${r.author}</p>
         <p class="review-text">
           ${r.review}
         </p>
       </li>`,h.reviewsList.appendChild(n)})}catch(o){console.error("Error fetching reviews:",o)}});const a=document.querySelector(".footer-form");a.addEventListener("submit",async function(o){o.preventDefault();const s=document.getElementById("user-email").value,r=document.getElementById("user-comment").value;if(!s||!r){alert("Please fill in both fields");return}localStorage.setItem("email",s),localStorage.setItem("comment",r);const n={email:s,comment:r};try{const t=await(await fetch("https://portfolio-js.b.goit.study/api-docs",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(n)})).json();t.error?console.log("Error: "+t.error):a.reset(),E.textContent=t.title,L.textContent=t.message,b()}catch(e){alert("Error: "+e.message)}});const c=document.querySelector(".footer-backdrop"),v=document.querySelector(".modal"),g=document.querySelector(".close-btn"),E=document.querySelector(".modal-title"),L=document.querySelector(".modal-message");function b(){c.classList.add("is-open")}function l(){c.classList.remove("is-open")}g.addEventListener("click",l);document.addEventListener("keydown",o=>{o.key==="Escape"&&c.classList.contains("is-open")&&l()});document.addEventListener("click",o=>{o.composedPath().includes(v)||l()});
//# sourceMappingURL=commonHelpers.js.map
