import{S as u,N as p,K as f,M as w,A as y,a as h}from"./assets/vendor-dce76c42.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();new u("#swiperAbout",{modules:[p,f,w],navigation:{nextEl:".about-me-btn-swipe"},mousewheel:{invert:!0},keyboard:{enabled:!0,onlyInViewport:!0},mousewheel:!0,touch:!0,centeredSlides:!1,loop:!0,speed:500,spaceBetween:0,slideToClickedSlide:!0,allowTouchMove:!0,slideActiveClass:"current-skill",slidesPerView:2,width:260,breakpoints:{768:{slidesPerView:3,width:600},1440:{slidesPerView:6,width:1264}}});const v=document.querySelectorAll(".ac-item-information");v.forEach(t=>{t.addEventListener("click",()=>{t.classList.toggle("active")})});new y(".faq-list",{elementClass:"faq-item",triggerClass:"faq-question",panelClass:"faq-answer",showMultiple:!0});const a={reviewsList:document.querySelector(".reviews-list"),previousBtn:document.querySelector(".previous-btn"),nextBtn:document.querySelector(".next-btn")};window.addEventListener("DOMContentLoaded",async()=>{try{const s=(await h.get("https://portfolio-js.b.goit.study/api/reviews?_id=7")).data;if(s.length===0){alert("No reviews found!");const r=document.createElement("p");r.innerText="Not found",a.reviewsList.appendChild(r)}else s.forEach(r=>{const n=document.createElement("div");n.classList.add("swiper-slide"),n.classList.add("review-item"),n.innerHTML=`<li class="reviews-item"> 
           <img  
             src="${r.avatar_url}"  
             alt="author's photo"  
              class="review-photo"  
           width="48px"  
           height="48px"  />  
           <p class="review-author">${r.author}</p>  
           <p class="review-text">${r.review}</p> 
        </li>`,a.reviewsList.appendChild(n)})}catch(t){console.error("Error fetching reviews:",t),alert("Error fetching reviews. Please try again later.")}});new u(".mySwiper",{direction:"horizontal",breakpoints:{1440:{slidesPerView:4},768:{slidesPerView:2},375:{slidesPerView:1}},navigation:{nextEl:".custom-next",prevEl:".custom-prev"},mousewheel:!0,keyboard:{enabled:!0},on:{reachEnd:function(){const t=document.querySelector(".custom-next");t.disabled=!0,t.style.opacity="0.5",t.removeEventListener("click",m)}}});function m(){}document.querySelector(".custom-next").addEventListener("click",m);const d=document.querySelector(".footer-form");d.addEventListener("submit",async function(t){t.preventDefault();const s=document.getElementById("user-email").value,r=document.getElementById("user-comment").value;if(!s||!r){alert("Please fill in both fields");return}localStorage.setItem("email",s),localStorage.setItem("comment",r);const n={email:s,comment:r};try{const o=await(await fetch("https://portfolio-js.b.goit.study/api-docs",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(n)})).json();o.error?console.log("Error: "+o.error):d.reset(),L.textContent=o.title,b.textContent=o.message,S()}catch(e){alert("Error: "+e.message)}});const c=document.querySelector(".footer-backdrop"),g=document.querySelector(".modal"),E=document.querySelector(".close-btn"),L=document.querySelector(".modal-title"),b=document.querySelector(".modal-message");function S(){c.classList.add("is-open")}function l(){c.classList.remove("is-open")}E.addEventListener("click",l);document.addEventListener("keydown",t=>{t.key==="Escape"&&c.classList.contains("is-open")&&l()});document.addEventListener("click",t=>{t.composedPath().includes(g)||l()});
//# sourceMappingURL=commonHelpers.js.map
